apiVersion: v1
entries:
  commonground-gateway:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2021-12-15T10:23:03.873045+01:00"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 10.9.5
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 15.3.2
    description: A Helm chart for Kubernetes
    digest: fee17a98ae10f61fd1e3ac7819c7c1b77ffc40ef6cc36590cf5bdf6557f1284e
    name: commonground-gateway
    type: application
    urls:
    - charts/commonground-gateway-0.1.5.tgz
    version: 0.1.5
  commonground-gateway-frontend:
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2021-12-15T10:23:03.865297+01:00"
    dependencies:
    - alias: gateway
      condition: gateway.enabled
      name: commonground-gateway
      repository: https://raw.githubusercontent.com/ConductionNL/commonground-gateway/master/api/helm/
      version: 0.1.5
    description: A Helm chart for the Verhuizen PWA of 's-Hertogenbosch
    digest: 05a7336885d70e22e9c843bb66bf20ae8cb9f0464f1a479510ad88eb0c288587
    name: commonground-gateway-frontend
    type: application
    urls:
    - commonground-gateway-frontend-0.1.0.tgz
    version: 0.1.0
generated: "2021-12-15T10:23:03.85306+01:00"
