apiVersion: v1
entries:
  commonground-gateway:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2022-06-14T10:49:24.8555696+02:00"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 10.9.5
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 15.3.2
    - name: rabbitmq
      repository: https://charts.bitnami.com/bitnami
      version: 9.0.1
    description: A Helm chart for Kubernetes
    digest: 61176b210c41b7f1153021924af204988fb50a0dbef2ed51856d5b98543078f7
    name: commonground-gateway
    type: application
    urls:
    - charts/commonground-gateway-0.1.7.tgz
    version: 0.1.7
  commonground-gateway-frontend:
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2022-06-14T10:49:24.8405137+02:00"
    dependencies:
    - alias: gateway
      condition: gateway.enabled
      name: commonground-gateway
      repository: https://raw.githubusercontent.com/ConductionNL/commonground-gateway/feature-cleanup/api/helm/
      version: 0.1.7
    description: A Helm chart for the Verhuizen PWA of 's-Hertogenbosch
    digest: 383b353dfd49e0a5bcc577fe40aec42cf2055ae2e93414f4d1833b076e1f57e6
    name: commonground-gateway-frontend
    type: application
    urls:
    - commonground-gateway-frontend-0.1.0.tgz
    version: 0.1.0
generated: "2022-06-14T10:49:24.825494+02:00"
